# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cli.ipynb.

# %% auto 0
__all__ = ['generate_sample_requirements_txt', 'generate_sample_readme_content', 'generate_sample_fasthtml_content',
           'generate_sample_dockerfile_content', 'generate_sample_cloudbuild_yaml_content', 'demo_garden_init',
           'demo_garden_build']

# %% ../nbs/00_cli.ipynb 2
from fastcore.script import *
import os
from pathlib import Path
from fh_bootstrap import *

# %% ../nbs/00_cli.ipynb 4
def generate_sample_requirements_txt():
    """Generates sample requirements.txt"""
    return """
python-fasthtml

    """

def generate_sample_readme_content():
    """Generates boiler plate README.md content"""
    return """
This is a sample demo using fasthtml. 

To run:

`pip install -r requirements.txt`

`python app.py`

    """

def generate_sample_fasthtml_content():
    """Generates boiler plate fasthtml content"""
    return """
# This was autogenerated as a sample application! 
from fh_bootstrap import *
app, rt = fast_app(pico=False, live=False)
        
@rt("/")
def get():
    return Titled(
            "Sample Demo",
            H1("This is a sample demo!")
            )
serve() 
"""

def generate_sample_dockerfile_content():
    """Generate boilerplate Dockerfile content."""
    return """
# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "app.py"]
"""

def generate_sample_cloudbuild_yaml_content():
    """Generate boilerplate cloudbuild.yaml content."""
    return """
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$REPO_NAME'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
"""

# %% ../nbs/00_cli.ipynb 5
@call_parse
def demo_garden_init(project_name: str = None, # this is the path for the directory you want demo garden to manage 
                    ):
    """Initializes a new Demo Garden project. Call this function when inside of the directory
    you want Demo Garden to manage. Using this like `git init`.
    """
    if project_name:
        project_dir = Path(project_name)
    else:
        project_dir = Path.cwd()
    if (project_dir / ".demogarden").exists():
        raise ValueError(f"Error: This is already a demogarden managed repository")
    if project_name and project_dir.exists():
        raise ValueError(f"Error: {project_name} already exists")

    (project_dir / "assets").mkdir(exist_ok=True)
    (project_dir / "demos").mkdir(exist_ok=True)
    (project_dir / "demos" / "Sample_Category" / "Demo_Name").mkdir(parents=True, exist_ok=True)
    with open(project_dir / "demos" / "Sample_Category" / "Demo_name" / "app.py", "w") as f:
        f.write(generate_sample_fasthtml_content())
    with open(project_dir / "demos" / "Sample_Category" / "Demo_Name" / "requirements.txt", "w") as f:
        f.write(generate_sample_requirements_txt())
    with open(project_dir / "demos" / "Sample_Category" / "Demo_Name" / "README.md", "w") as f:
        f.write(generate_sample_readme_content())

    # Generate Dockerfile for Demo Garden System. This is something that won't be configured by the user
    with open(project_dir / "Dockerfile", "w") as f:
        f.write(generate_sample_dockerfile_content())
    with open(project_dir / "cloudbuild.yaml", "w") as f:
        f.write(generate_sample_cloudbuild_yaml_content())
        
    with open(project_dir / "demos" / "Sample_Category" / "Demo_Name" / "Dockerfile", "w") as f:
        f.write(generate_sample_dockerfile_content())

    with open(project_dir / "demos" / "Sample_Category" / "Demo_Name" / "cloudbuild.yaml", "w") as f:
        f.write(generate_sample_cloudbuild_yaml_content())

    (project_dir / "app.py").touch()
    (project_dir / ".demogarden").touch()
    
    print(f"Demo Garden project initialized successfully in {project_dir}")

# %% ../nbs/00_cli.ipynb 6
@call_parse
def demo_garden_build():
    """Build the Demo Garden project."""
    if not Path(".demogarden").exists():
        raise ValueError("Error: Not a demo garden project. Run 'demo_garden_init' to initialize this repository ")
        
